### ISSUE TITLE
Style/SignalException はsemanticの方が良いのではないか

### ISSUE THREAD

**Issue by naoshihoshi** [pixta-dev/pixta-rubocop#3]
`only_raise`ではなく、`semantic`(デフォルト)を使いたいのですが、いかがでしょうか？

理由はrescueなどで捕捉した例外を再度発生させない場合でも、必ずraiseを使用しなくてはならないためです。

**Comment by necojackarc** [comment]
個人的意見の前に客観的な補足事項を書いておきます。
1. RuboCop 最新バージョンでのデフォルトは`only_raise`です。
   - バージョン差異をなくすために、設定ファイルには`only_raise`を明記してます。
2. Ruby Style Guide でも [raise を使うように推奨](https://github.com/bbatsov/ruby-style-guide#prefer-raise-over-fail)されています（本日時点での日本語版は古い）。
   - この変更に至った流れはこちらから見れます。
     - [Exceptions should favor `raise` over `fail`](https://github.com/bbatsov/ruby-style-guide/issues/512)
     - [Remove distinction between fail and raise](https://github.com/bbatsov/ruby-style-guide/pull/517)
     - [Inconsistence between ruby-style-guide for fail/raise and rubocop implementation](https://github.com/bbatsov/ruby-style-guide/pull/517)

そのため、ピクスタコーディングルールの「基本的には Ruby Style Guide に従う」というモットーから、現在は`only_raise`としています。

**Comment by necojackarc** [comment]
個人的には現在の Ruby Sytle Guide 推奨のデフォルト設定`only_raise`に賛成です。

昔は自分も @naoshihoshi さんと同様、`raise`と`fail`をかつての Ruby Style Guide に合わせて文脈で使い分けていたのですが、振り返ってみると、`raise`と`fail`を使い分けるメリットは皆無だったかなと感じます。

それどころか、文脈に合わせて書いてくれとコードレビューで説明する必要があったというデメリット（ベトナムからの PR で何度かこのコメントしましたが、今思うと無駄な労力 :sob:）の方が大きかったような気がします。

完全に同じメソッドですので、`map`/`collect`, `reduce`/`inject` と同様に、組織としてどちらを使うか決めておいたほうが混乱が防げると思います :smile:

ref: [Ruby のココがダメ#メソッド名の別名がありすぎ](http://qiita.com/scivola/items/17470c52641d3ffa1650#%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E5%90%8D%E3%81%AE%E5%88%A5%E5%90%8D%E3%81%8C%E3%81%82%E3%82%8A%E3%81%99%E3%81%8E)

**Comment by yasaichi** [comment]
@naoshihoshi 

> 理由はrescueなどで捕捉した例外を再度発生させない場合でも、必ずraiseを使用しなくてはならないためです。

具体例を示していただけますか？
@necojackarc に正しく意図が伝わっていない気がします。

**Comment by necojackarc** [comment]
> 理由はrescueなどで捕捉した例外を再度発生させない場合でも、必ずraiseを使用しなくてはならないためです。

@yasaichi くんの言うとおりで、正直これがどういうことかわかってないです。笑
そのため、上では「こういう理由で`only_raise`に賛成」ということだけ書いてます。

**Comment by naoshihoshi** [comment]
- 今後新しく入る人はstyle guide をお手本にする(であろう)
- pixtaリポジトリではfailを書いているところがほぼない

上記のため、`only_raise`で良いのではないかと！

**Comment by necojackarc** [comment]
:+1:
